redis:
  image: redis
  container_name: cache
  expose:
    - 6379
app:
  build: ./
  volumes:
    - ./:/var/www/app
  ports:
    - 3000:3000
  environment:
    - NODE_ENV=development
    - PORT=3000
    - REDIS_URL=redis://cache
  command:
    sh -c 'npm i && npm run start'