services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  cache-invalidation-service:
    build: 
      context: ./
      dockerfile: ./cache-invalidation-service/Dockerfile
    volumes:
      - ./cache-invalidation-service:/var/www/app
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://cache
      - INFURA_WEBSOCKET_URL=wss://mainnet.infura.io/ws/v3/4e1a1225c8b64371b824946a2fac51a8
    command:
      sh -c 'npm i && npm run start'
    depends_on:
      - redis
  app:
    build: 
      context: ./
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/var/www/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://cache
      - INFURA_WEBSOCKET_URL=wss://mainnet.infura.io/ws/v3/4e1a1225c8b64371b824946a2fac51a8
    command:
      sh -c 'npm i && npm run start'
    depends_on:
      - redis
      # - cache-invalidation-service
    restart: always